- name: play1
  hosts: localhost
  tasks:
   - name: play1 and task1
     ansible.builtin.debug:
       msg: "play 1 and task 1"
- name: play2
  host: localhost
  tasks:
   - name: play2 and task2
     ansible.builtin.debug:
       msg: "play 2 and task 2"
      

