- name: variables
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: printing details
    ansible.builtin.debug:
      msg: "Hi I am learning {{Course}} triner is {{Trainer}} days is {{Days}}"