- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: user
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: yes
  - name: printing user
    ansible.builtin.debug:
      msg: "user output {{user}}"
  - name: creating user
    ansible.builtin.user:
      name: roboshop
    when: "{{user.rc}} != 0"