- name: working wih loop
  hosts: localhost
  become: yes
  tasks:
  - name: install package
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.present}}"
    loop:
    - {name: "git",state: "present"}
    - {name: "mysql",state: "absent"}
    - {name: "postfix",state: "present"}